### ISSUE TITLE
Backend should has a route for handling redirect_uri

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/oauth2-tester#8]
Backend should has the base route for handling callback errors. **Important point**: the registered callback address should be the base address for auth code callback and for the token callback. 
- [ ] GET `/callback?code=` - redirect to the frontend (payload: code & referrer?)
- [ ] GET `/callback?error=` - redirect to the frontend (payload: error & referrer?)
- [ ] GET `/callback?access_token=` - should complete the frondend "exchangeAuthCode" request #7 with token
- [ ] POST `/callback` + { access_token } - should complete the frondend "exchangeAuthCode" request #7 with error
- [ ] POST `/callback` + { error } - should complete the frondend "exchangeAuthCode" request #7 with error

**Comment by sedovalx** [comment]
non actual - no need in additional error endpoint
